# Generated by Django 3.2 on 2022-06-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='blog_image',
        ),
    ]
