# Generated by Django 3.2 on 2022-06-07 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_remove_tenant_blog_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={},
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='blog_name',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='featured',
        ),
    ]
